OPENAI_API_KEY = 'OPENAI_API_KEY'
ACTIVELOOP_TOKEN='ACTIVELOOP_TOKEN'
SERPAPI_API_KEY = 'SERPAPI_API_KEY'
OPENWEATHERMAP_API_KEY = 'OPENWEATHERMAP_API_KEY'
APIFY_API_TOKEN = 'APIFY_API_TOKEN'
logging_address = 'logging_address
log_port = 27057